### ISSUE TITLE
Code Completion Checklist

### ISSUE THREAD

**Issue by Maxwell-lt** [Maxwell-lt/PersistentTally#4]
- [ ] New List File dialog box completion
- [ ] Main Window
  - [ ] Populate window with contents of a list file
  - [ ] Arrange arbitrary numbers of items in a window
  - [ ] Buttons for increment/decrement functionality
  - [ ] Add new items to a list
  - [ ] Change list from main window
  - [ ] Have main window be the parent window
- [ ] Figure out what manifests are going to do
